### ISSUE TITLE
为啥右侧的配置都不可用？

### ISSUE THREAD

**Issue by JasonkayZK** [wangrongding/love-collection#1]
为啥右侧的配置都不可用？
![image](https://user-images.githubusercontent.com/40811521/129469500-e0edcf20-256c-46b9-8a47-09ab434eb7a7.png)

**Comment by wangrongding** [comment]
你好~目前功能区的其他功能正在完善中噢~晚点我会更新README文件对项目进行说明🥳

**Comment by JasonkayZK** [comment]
好的，那其他功能大概多久可以完成呢？比较期待！
